CHAT_PAGE = r'''<!doctype html>
<html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI is LOVE · Mira</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f6f1ea;color:#283630;font:16px system-ui,sans-serif}main{max-width:760px;margin:auto;height:100dvh;display:flex;flex-direction:column;padding:20px}header{border-bottom:1px solid #ddd5c9;padding:8px 0 16px;display:flex;align-items:center;gap:14px}.avatar{border-radius:50%;background:#476d5b;color:white;font-size:24px;padding:14px 20px}h1{font-size:22px;margin:0}small{color:#64736a}.auth{margin:auto;max-width:340px}input,textarea,button{font:inherit;border-radius:12px;border:1px solid #b8c5bc;padding:12px}input{width:100%;margin:12px 0}button{background:#365d4c;color:white;cursor:pointer}button:disabled{opacity:.5;cursor:default}#messages{flex:1;overflow:auto;padding:24px 0}.bubble{max-width:85%;padding:12px 16px;margin-bottom:6px;border-radius:18px;white-space:pre-wrap;overflow-wrap:anywhere}.player{background:#dbe8dd;margin-left:auto}.mira{background:white;border:1px solid #e4ded5}.stamp{font-size:12px;color:#748077;margin:0 6px 16px}.right{text-align:right}#compose{display:flex;gap:10px}textarea{resize:none;flex:1;min-width:0;background:#fff}#status{min-height:26px;font-size:14px;color:#66736c;padding:5px 0}.hidden{display:none!important}#retry{align-self:flex-start;margin-bottom:8px}
</style><main><header><div class="avatar" aria-hidden="true">M</div><div><h1>Mira</h1><small>留一段話給她</small></div></header>
<section class="auth" id="auth"><h2>我們的聊天</h2><p>輸入測試通行碼，繼續和 Mira 聊天。</p><form id="unlock"><input id="code" type="password" autocomplete="off" aria-label="測試通行碼" required><button>開始聊天</button></form><p id="authError" role="alert"></p></section>
<div id="messages" class="hidden" aria-live="polite"></div><div id="status" role="status"></div><button id="retry" class="hidden">重試這則訊息</button><form id="compose" class="hidden"><textarea id="text" maxlength="2000" rows="2" placeholder="想跟 Mira 說什麼？" aria-label="訊息" required></textarea><button id="send">傳送</button></form></main>
<script>
'use strict';let token='',pending=null,busy=false;const $=id=>document.getElementById(id);
async function api(method,body){const r=await fetch('/chat',{method,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error(r.status===401?'通行碼不正確。':r.status===503?'聊天暫時尚未開放。':r.status===409?'Mira 還在回覆，請稍後重試。':'目前無法取得回覆，請重試原訊息。');return r.json();}
function bubble(text,role,time){const b=document.createElement('div');b.className='bubble '+role;b.textContent=text;$('messages').append(b);const t=document.createElement('div');t.className='stamp'+(role==='player'?' right':'');t.textContent=new Date(time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('messages').append(t);}
function render(turns){$('messages').replaceChildren();for(const t of turns){bubble(t.player_text,'player',t.received_at);if(t.reply)bubble(t.reply,'mira',t.replied_at);}if(!turns.length){const p=document.createElement('p');p.textContent='從一句你好開始。';$('messages').append(p);}$('messages').scrollTop=$('messages').scrollHeight;}
function controls(){ $('send').disabled=busy||!!pending;$('text').disabled=busy||!!pending;$('retry').classList.toggle('hidden',!pending||busy);}
$('unlock').onsubmit=async e=>{e.preventDefault();token=$('code').value;try{const h=await api('GET');$('code').value='';$('auth').classList.add('hidden');$('messages').classList.remove('hidden');$('compose').classList.remove('hidden');render(h.turns);const t=h.turns.find(t=>!t.reply);if(t)pending={request_id:t.id,text:t.player_text};controls();}catch(e){token='';$('authError').textContent=e.message;}};
async function transmit(){busy=true;controls();$('status').textContent='Mira 正在回覆…';try{await api('POST',pending);pending=null;$('text').value='';render((await api('GET')).turns);$('status').textContent='';}catch(e){$('status').textContent=e.message;}finally{busy=false;controls();}}
$('compose').onsubmit=e=>{e.preventDefault();const text=$('text').value.trim();if(!text||busy||pending)return;pending={request_id:crypto.randomUUID(),text};transmit();};$('retry').onclick=()=>transmit();
</script></html>'''
